fuel-prices:
  scheduled-update:
    cron: 0 0 6 * * ?
  scraper:
    currency: USD
    rateLimit:
      refreshPeriod: 1s
      limitForPeriod: 5
      timeoutDuration: 1m
    site:
      base-url: https://www.globalpetrolprices.com/
      diesel-prices-endpoint: /diesel_prices/
      gasoline-prices-endpoint: /gasoline_prices/

springdoc:
  swagger-ui:
    path: /swagger-ui.html

currency:
  api:
    api-key: todo
    base-url: https://openexchangerates.org
    endpoints:
      exchange-rates: /api/latest.json
      currencies: /api/currencies.json

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/reline?authSource=admin
      database: reline
      authentication-database: admin
      auto-index-creation: true
  security:
    user:
      password: password
logging:
  level:
    root: INFO
    com.traanite.reline.*: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info"